osx_image: xcode8
xcode_sdk: iphonesimulator10.0
language: objective-c

xcode_workspace: Example/EVSlidingTableViewCell.xcworkspace
xcode_scheme: EVSlidingTableViewCell-Example

env:
  - DESTINATION="OS=9.0,name=iPhone 6"
  - DESTINATION="OS=9.1,name=iPhone 6 Plus"
  - DESTINATION="OS=9.2,name=iPhone 6S"
  - DESTINATION="OS=9.3,name=iPhone 6S Plus"
  - DESTINATION="OS=10.0,name=iPhone 7"

matrix:
  include:
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.1,name=iPhone 4S"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.2,name=iPhone 5"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.3,name=iPhone 5S"
    - osx_image: xcode7.3
      xcode_sdk: iphonesimulator9.3
      env: DESTINATION="OS=8.4,name=iPhone 6"

script: set -o pipefail && xcodebuild -workspace $TRAVIS_XCODE_WORKSPACE -scheme $TRAVIS_XCODE_SCHEME -sdk $TRAVIS_XCODE_SDK -destination "$DESTINATION" build test | xcpretty -c
- pod lib lint
